### ISSUE TITLE
Port improved TokenRegistry implementation back to future/peggy2

### ISSUE THREAD

**Issue by smartyalgo** [Sifchain/sifnode#2419] opened 2022-02-01 16:56 UTC
We made improvements in tokenregistry module, that was removed in the develop merge. 

Deliverable:
Replace existing impl with improved impl 
Potentially merge this into develop independently to avoid future merge conflicts

**Comment by pandaring2you** [comment] 2022-02-18 00:16
will do this after group 1 integration tests

**Comment by pandaring2you** [comment] 2022-03-17 23:16
Duplicate of Junius's task

**Closed by pandaring2you** 2022-03-17 23:16 UTC
Labels: Peggy Team
