### ISSUE TITLE
Add feature to integration test environment to allow using geth (ropsten, private geth network etc) instead of ganache for local test

### ISSUE THREAD

**Issue by ElliotFriedman** [Sifchain/sifnode#963] opened 2021-03-17 18:52 UTC
Comment:

There are still a couple details to clean up, and it got kicked out of being the top item on my priority list. We can run test_eth_transfers against a local geth, and we can run selected tests against testnets (sandpit, swing-set).

**Comment by banshee** [comment] 2021-03-26 22:12
Duplicate of https://github.com/Sifchain/issues/issues/92

**Closed by banshee** 2021-03-26 22:12 UTC
Labels: Tech Arch Discussion, Testing
