### ISSUE TITLE
Group 2 Integration Tests: Transfer a double-pegged Token, IBC token, and Rowan token - to EVM chain and back

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/sifnode#2158] opened 2021-11-12 01:28 UTC

**Comment by pandaring2you** [comment] 2022-02-10 23:52
Proposed coordination: Since we're all in different timezones, the proposal is to hand off the work to the person in the next time zone.

**Comment by pandaring2you** [comment] 2022-02-18 00:21
https://sifchain.slack.com/archives/C01ERUNS2Q0/p1645098089028009
Junius

Hi, I have a technical issue about the IBC token. I am working at the peggy integration test. The test case is to export ibc token that we received from other cosmos chain, to Ethereum. I create and mint a token with denom prefix as "ibc/" in the genesis, then try to lock the token in sifnode side. But the transaction always failed, from the backend I can see the error message like
{"level":"debug","module":"state","code":111222,"log":"panic message redacted to hide potentially sensitive system info: panic","time":"2022-02-17T08:22:24+08:00","message":"invalid tx"}
I appreciate if IBC expert here can help me to figure out what's the issue and how to fix it. thanks!
3 replies

_IM  12 hours ago
@junius zhou I might be stating the obvious here (so apologies if you've already looked into this), but have you tried increasing the log level to get more detail?

junius zhou  12 hours ago
Will change the log level and get more info, thanks! @_IM

Tim Lind  7 hours ago
I believe you might need to use the --trace flag to get that unredacted.

**Comment by pandaring2you** [comment] 2022-02-18 00:24
@juniuszhou to check with @banshee if above solution doesnt work, Brandon mentioned James resolved this issue before.

**Comment by pandaring2you** [comment] 2022-02-18 00:27
Est ETA - highly dependent on Mock token issues being resolved - 3/2

**Comment by juniuszhou** [comment] 2022-02-18 05:19
After print out the call stack, I found the root cause for the failed tx, it is a bug in sifnode code. The map not init before set its value. Sorry for it, will fix it immediately.

**Comment by pandaring2you** [comment] 2022-02-24 23:40
On track to finish next week. Issue #2483 (PR#2484) to be reviewed by @Brando753

**Comment by pandaring2you** [comment] 2022-03-03 23:36
All test cases are now passing! After review from Brando, we should be wrapped with this task.

**Comment by pandaring2you** [comment] 2022-03-10 23:59
Awaiting final review from @Brando753

**Comment by pandaring2you** [comment] 2022-03-15 16:40
Junius to re-write tests into Python as these were more complicated than originally thought. In a separate task assigned to junius.

**Comment by pandaring2you** [comment] 2022-03-17 22:50
#2540 #2543

**Comment by pandaring2you** [comment] 2022-03-22 16:38
Clearing up lock/burn side. Junius working on converting this to the burn side. ex import shiba -> sifchain (lock) -> bsc (burn original). Basically, any time a token is not native to the origin chain, burn it.

**Comment by juniuszhou** [comment] 2022-03-26 14:16
close it since we will not merge the code for group2 in typescript.

**Closed by juniuszhou** 2022-03-26 14:16 UTC
Labels: Peggy Team
