### ISSUE TITLE
[Peggy] peggy:lock for eth does not work

### ISSUE THREAD

**Issue by ilyabukalov** [Sifchain/sifnode#341] opened 2020-12-03 10:54 UTC
smart contract + relayer process it correctly (eth is locked in Bridge contract correctly) but cosmos transaction is rejected on sifnode side.
Commit: 554bf5639a8338e2853ffe652ae7b9fbe0cafff0
To reproduce on fresh install:
```
./scripts/init.sh
cd smart-contracts
yarn develop
yarn migrate
sifnoded start
export ETHEREUM_PRIVATE_KEY=c87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3 # which is INITIAL_VALIDATOR_ADDRESSES
ebrelayer init tcp://localhost:26657 ws://localhost:7545/ 0xdDA6327139485221633A1FcD65f4aC932E60A2e1 akasha <akasha's mnemonic> --chain-id=sifchain
yarn peggy:lock $(sifnodecli keys show akasha -a) eth 100 <sender account>
```

On the same setting command works correctly:
```
sifnodecli tx ethbridge lock $(sifnodecli keys show akasha -a) 0xf17f52151EbEF6C7334FAD080c5704D77216b732 1 rowan --ethereum-chain-id=5777 --from=akasha --yes
```

**Comment by utx0** [comment] 2020-12-08 05:02
Hey mate, this bug doesnt tell me anything about what you are saying with `cosmos transaction is rejected on sifnode side.` can you please provide more details, logs etc? I feel you also might have a local development setup issue as this is working in testnet.

**Comment by ElliotFriedman** [comment] 2020-12-08 06:14
Why is address 0 being passed to the peggy:lock yarn command?

**Comment by ElliotFriedman** [comment] 2020-12-08 06:14
Please use scripts/sendLock.js directly when sending lock transactions.

**Comment by ilyabukalov** [comment] 2020-12-08 07:00
> Why is address 0 being passed to the peggy:lock yarn command?

it is alias for "eth". It does not matter. I changed to 'eth' in cmd

**Comment by ilyabukalov** [comment] 2020-12-08 07:07
Log of relayer. It receives and process web3 event but cosmos rejects the transaction
--
I[2020-12-08|14:56:41.465] Starting WSEvents service                    impl=WSEvents
I[2020-12-08|14:56:41.467] Started Ethereum websocket with provider:    ws://localhost:7545/=(MISSING)
I[2020-12-08|14:56:41.495] Subscribed to bridgebank contract at address: 0x75c35C980C0d37ef46DF04d31A140b65503c0eEd 
I[2020-12-08|15:04:12.193] Witnessed tx 0x3ea03a29c0ed5eb4f1df2b5eb20e5462ea01d4c4850adfb19e2c1d06c19fe920 on block 21
 
2020/12/08 15:04:12 Found event from the ethereum bridgebank contract:  LogLock
2020/12/08 15:04:12 Found loglock event from the ethereum bridgebank contract:  LogLock
I[2020-12-08|15:04:12.193] 
Chain ID: 5777
Bridge contract address: 0x75c35C980C0d37ef46DF04d31A140b65503c0eEd
Token symbol: ETH
Token contract address: 0x0000000000000000000000000000000000000000
Sender: 0xf17f52151EbEF6C7334FAD080c5704D77216b732
Recipient: sif1l7hypmqk2yc334vc6vmdwzp5sdefygj2ad93p5
Value: 100
Nonce: 2
Claim type: lock 
{
  "height": "0",
  "txhash": "47289B1972E82AECF75DDC9CC49C1A29BEC67431D5362790FEFE65588D884D56",
  "raw_log": "[]"
}
I[2020-12-08|15:04:17.153] New transaction witnessed

**Comment by ilyabukalov** [comment] 2020-12-08 07:08
Sifnoded log (invalidTxs=1). 
--
I[2020-12-08|15:04:17.135] Executed block                               module=state height=526 validTxs=0 invalidTxs=1
I[2020-12-08|15:04:17.143] Committed state                              module=state height=526 txs=1 appHash=89EB75E84BF2775FBC1127A63091C525FF17132E164D0596D8EA0EEB9331FEF2

**Comment by ilyabukalov** [comment] 2020-12-08 07:10
> Please use scripts/sendLock.js directly when sending lock transactions.

it is exactly how I described it. Isn't? Anyway problem is not on the truffle scripts side.

**Comment by ElliotFriedman** [comment] 2020-12-08 07:53
What branch were you on when this came up? Were you on the latest version of develop? Did your sifchain address show when you ran this?

`$(sifnodecli keys show akasha -a)`

**Comment by ilyabukalov** [comment] 2020-12-08 08:15
> What branch were you on when this came up? Were you on the latest version of develop?

commit attached in head.

**Comment by ilyabukalov** [comment] 2020-12-08 08:16
> Did your sifchain address show when you ran this?
> 
> `$(sifnodecli keys show akasha -a)`

yes sure, Initialized by 
`
#!/usr/bin/env bash
rm -rf ~/.sifnoded
rm -rf ~/.sifnodecli

sifnoded init test --chain-id=sifchain

sifnodecli config output json
sifnodecli config indent true
sifnodecli config trust-node true
sifnodecli config chain-id sifchain
sifnodecli config keyring-backend test

echo "Generating deterministic account - shadowfiend"
echo "race draft rival universe maid cheese steel logic crowd fork comic easy truth drift tomorrow eye buddy head time cash swing swift midnight borrow" | sifnodecli keys add shadowfiend --recover

echo "Generating deterministic account - akasha"
echo "hand inmate canvas head lunar naive increase recycle dog ecology inhale december wide bubble hockey dice worth gravity ketchup feed balance parent secret orchard" | sifnodecli keys add akasha --recover

sifnoded add-genesis-account $(sifnodecli keys show shadowfiend -a) 1000000000rwn,1000000000catk,1000000000cbtk,1000000000ceth,100000000stake
sifnoded add-genesis-account $(sifnodecli keys show akasha -a) 1000000000rwn,1000000000catk,1000000000cbtk,1000000000ceth,100000000stake

sifnoded gentx --name shadowfiend --keyring-backend test

echo "Collecting genesis txs..."
sifnoded collect-gentxs

echo "Validating genesis file..."
sifnoded validate-genesis
`

**Comment by ElliotFriedman** [comment] 2020-12-08 20:46
I'm running this off the latest dev branch and it is not giving me any problems. I cannot reproduce your error.

**Comment by ilyabukalov** [comment] 2020-12-09 02:26
> I'm running this off the latest dev branch and it is not giving me any problems. I cannot reproduce your error.

Did I understand you correctly that after command:
```
yarn peggy:lock $(sifnodecli keys show akasha -a) eth 100 0xf17f52151EbEF6C7334FAD080c5704D77216b732
```
you observed increase of balance by 100 on ceth symbol:
```
sifnodecli query account $(sifnodecli keys show akasha -a)
```

**Comment by EddCS** [comment] 2020-12-11 13:54
@ilchebedelovski could you share the .env file you used for this?

**Comment by ilyabukalov** [comment] 2020-12-12 01:18
> @ilchebedelovski could you share the .env file you used for this?
.env is standard taken from:
```
cd smart-contracts
cp .env.example .env
```

**Comment by EddCS** [comment] 2020-12-14 17:20
I've recreated this issue successfully with the latest version of `sifnodecli`. If I run 

```
sifnodecli tx ethbridge lock $(sifnodecli keys show akasha -a) <ETHEREUM_ADDRESS> 1 rowan --ethereum-chain-id=5777 --from=akasha --yes
```

I can see the amount removed from the `akasha` account:
```
sifnodecli query account $(sifnodecli keys show akasha -a)      
{
  "type": "cosmos-sdk/Account",
  "value": {
    "address": "sif1l7hypmqk2yc334vc6vmdwzp5sdefygj2ad93p5",
    "coins": [
      {
        "denom": "catk",
        "amount": "1000000000"
      },
      {
        "denom": "cbtk",
        "amount": "1000000000"
      },
      {
        "denom": "cdash",
        "amount": "1000000000"
      },
      {
        "denom": "ceth",
        "amount": "1000000000"
      },
      {
        "denom": "rowan",
        "amount": "999999998"
      },
      {
        "denom": "stake",
        "amount": "100000000000"
      }
    ],
    "public_key": {
      "type": "tendermint/PubKeySecp256k1",
      "value": "A0mB4PyE5XeS3sNpFXIX536INyNoJHkMu1DEQ8FgH8Mq"
    },
    "account_number": "3",
    "sequence": "2"
  }
}
```

however if I run:
```
 yarn peggy:lock $(sifnodecli keys show akasha -a) eth 100
```

the values in the account don't change:
```
sifnodecli query account $(sifnodecli keys show akasha -a)                                                                            
{
  "type": "cosmos-sdk/Account",
  "value": {
    "address": "sif1l7hypmqk2yc334vc6vmdwzp5sdefygj2ad93p5",
    "coins": [
      {
        "denom": "catk",
        "amount": "1000000000"
      },
      {
        "denom": "cbtk",
        "amount": "1000000000"
      },
      {
        "denom": "cdash",
        "amount": "1000000000"
      },
      {
        "denom": "ceth",
        "amount": "1000000000"
      },
      {
        "denom": "rowan",
        "amount": "999999998"
      },
      {
        "denom": "stake",
        "amount": "100000000000"
      }
    ],
    "public_key": {
      "type": "tendermint/PubKeySecp256k1",
      "value": "A0mB4PyE5XeS3sNpFXIX536INyNoJHkMu1DEQ8FgH8Mq"
    },
    "account_number": "3",
    "sequence": "2"
  }
}
```

while the commands output looks correct:
```
yarn peggy:lock $(sifnodecli keys show akasha -a) eth 100                                                                            
yarn run v1.22.4
$ npx truffle exec scripts/sendLockTx.js sif1l7hypmqk2yc334vc6vmdwzp5sdefygj2ad93p5 eth 1
Using network 'ganache'.

Expected usage: 
truffle exec scripts/sendLockTx.js --network ropsten sif1nx650s8q9w28f2g3t9ztxyg48ugldptuwzpace eth 100

Connecting to contract....
Connected to contract, sending lock...
Sent lock...
{
  to: '0x736966316c376879706d716b327963333334766336766d64777a70357364656679676a32616439337035',
  from: '0x627306090abaB3A6e1400e9345bC60c78a8BEf57',
  symbol: 'ETH',
  token: '0x0000000000000000000000000000000000000000',
  value: 1,
  nonce: 4
}
Done in 2.15s.
```

**Comment by ilyabukalov** [comment] 2020-12-15 00:48
Thanks @EddCS . Very helpful.

**Comment by banshee** [comment] 2021-01-06 23:50
This is covered in the integration tests, in test/integration/initial_test_balances.py to set up the initial balances for a test user.

**Comment by banshee** [comment] 2021-01-06 23:54
Also

> This is covered in the integration tests, in test/integration/initial_test_balances.py to set up the initial balances for a test user.

Also in test/integration/peggy-e2e-test.py, in test_case_1, and in test_balance_does_not_change_without_manual_block_advance.  The second one of those tests behavior that's changed from the time this bug was filed.

(Also for future reference, the expected behavior is different now.  You'll need to advance at least 50 blocks before you'll see the balance change on sifchain.)

**Comment by ElliotFriedman** [comment] 2021-01-07 00:00
Closing as we test this in the CICD pipeline.

**Closed by ElliotFriedman** 2021-01-07 00:00 UTC
