### ISSUE TITLE
Migrate eRowan to Rowan

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/sifnode#1594] opened 2021-07-08 23:25 UTC
https://docs.google.com/document/d/1rJzIB8js2DGa7QDHYtmbBxWkaxILC2GRTJw-rWgAY4o/edit

**Comment by ElliotFriedman** [comment] 2021-07-20 19:58
@banshee Will now take point on integrating this code into the bridgebank.

**Comment by banshee** [comment] 2021-08-09 16:50
Duplicate of https://github.com/Sifchain/peggy/issues/108, so closing this one.

**Closed by banshee** 2021-08-09 16:50 UTC
Labels: Peggy, Peggy 2.0
