### ISSUE TITLE
Deploy cosmos v0.43 to TestNet

### ISSUE THREAD

**Issue by timlind** [Sifchain/sifnode#2252] opened 2021-12-06 18:09 UTC
To re-enable support for keplr ledger deploy an earlier version of the SDK to TestNet. Match the version that osmosis has deployed.

**Comment by ajoslin** [comment] 2021-12-06 18:11
👀 let me know if you want help testing this

**Comment by ajoslin** [comment] 2021-12-07 01:15
This would still include IBC v2 right?

**Comment by Jedi2002** [comment] 2021-12-07 01:46
Sure @ajoslin ,ill reach out as soon as I have it deployed on testnet.
It will include ibc v2

**Comment by ajoslin** [comment] 2021-12-07 01:52
## Summary of issue

0.44 is incompatible with Amino transactions, and fully deprecates them.  This is totally incompatible with Ledger, which is only compatible with Amino transactions, not protobuf.

We looked into what Osmosis & Emeris are doing with their 0.44 upgrade. Tested both out and found that they are still using Amino transactions, and do work with Ledger. This means they can't have done the same upgrade we did, since our version of 0.44 does not work with Amino transactions.

Emeris isn't open source, I've reached out to them to ask them what they are doing here too. Haven't heard back yet.
We looked at Osmosis backend source and @Tim Lind / @Tanmay say they are using some sort of custom fork of 0.44 that still enables Amino transactions - they can provide more details.

It does appear that the plain 0.44 upgrade we've done is not going to work. 

It looks like @Jedi2002 has a fix nearly ready.

**Comment by pandaring2you** [comment] 2022-01-11 18:50
@marshsif - since testnet is not currently working - can we re-open this or is there another task to track the status of testnet?

**Comment by marshsif** [comment] 2022-01-11 20:59
The team is currently testing v.43, and IBC Juno imports and exports. We'll likely need additional testing and an outside audit prior to betanet.

**Comment by pandaring2you** [comment] 2022-01-13 23:32
@marshsif - the peggy team is thinking of merging develop to future/peggy2 . do you think we'll be in a stable state on develop for us to begin our merge (est. early next week)

cc @Brando753 @smartyalgo @jzvikart @juniuszhou

**Comment by marshsif** [comment] 2022-01-14 15:23
@pandaring2you yes I think so. We still have a full regression test to run on TestNet to be certain. There is one issue we're still trying to figure out, with IBC tx's getting stuck in queues and requiring the queues to be manually cleared. We've no idea why that is intermittently happening with each of the IBC chains.

**Comment by smartyalgo** [comment] 2022-01-17 17:52
@marshsif , circling back, has the fix been merged into develop? if not, is there a ticket to track this issue?

**Comment by smartyalgo** [comment] 2022-01-17 18:09
to be clear, we dont think this blocks us from merging develop into future/peggy2 since it doesnt affect peggy functions.

**Comment by marshsif** [comment] 2022-01-18 14:44
Hey @pandaring2you @smartyalgo the .43 release is undergoing regression testing on DevNet today. So far, we're only aware of one intermittent issue that only appeared on TestNet, and we've not found the root cause. In general, testing has been going well up to today. I'd say it is looking pretty good, but if you want to be safe you could wait for the regression testing work to finish. I'll create a ticket for that now.

**Closed** 2022-02-17 20:49 UTC
Labels: Sifnode Team
