### ISSUE TITLE
Give all JSON logs a unique key in relayers

### ISSUE THREAD

**Issue by ElliotFriedman** [Sifchain/sifnode#1010] opened 2021-03-26 19:27 UTC
Currently, our JSON logs in the relayers have a bunch of information, however, there is not an easy way to search the logs for different types of events happening. To support this, all of our logs need the same key `eventType` that has a unique value based on what event is happening in the code. This will allow us to sort through large amounts of logs and make sense of different things that are happening in a faster way.

**Comment by pandaring2you** [comment] 2021-03-29 19:24
duplicate of pegg#49

**Closed** 2021-03-29 19:25 UTC
Labels: Peggy
