### ISSUE TITLE
Construct a mapping for IBC imports/exports under different denom

### ISSUE THREAD

**Issue by Brando753** [Sifchain/sifnode#2362] opened 2022-01-14 19:18 UTC
Since peggy 2 uses a new denom structure assets already exported by IBC need to be mapped to the new denom structure so that they when imported back in are credited as the correct token/asset.

We can hand this json mapping and sifnoded team will take over integrating into their ibc module

**Comment by pandaring2you** [comment] 2022-03-10 23:32
Duplicate of #2414

**Closed by pandaring2you** 2022-03-10 23:32 UTC
Labels: Peggy Team
